modLoader = "javafml" #mandatory
loaderVersion = "${forge_loader_version_range}" #mandatory
license = "${license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]] #mandatory
modId = "bitter_brews" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/bitter-brews" #optional
logoFile = "${mod_id}.png" #optional
authors = "${mod_author}" #optional
description = '''${description}''' #mandatory

[[dependencies.bitter_brews]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.bitter_brews]]
modId="tipsylib" #mandatory
mandatory=true #mandatory
versionRange="[2.0.4,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.bitter_brews]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
